version: '3.4'

services:
  pastamailer:
    restart: unless-stopped
    image: pastamailer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 1492:4000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb: 
    restart: unless-stopped
    image: mongo:4.4.6
    ports: 
      - 27017:27017
    volumes:
      - data:/data/db


volumes: 
  data: